version: '2'
services:
  mysql:
    image: mysql:5.5
    ports:
     - 3306
    environment:
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  memcached:
    image: memcached:1.4
    ports:
      - 11211
    command: [-n 256, -p 11211] 
